<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UserSecretsId>dotnet-PrintAgent.Host-572eb9c7-5776-451b-bb51-baba282eb744</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrintAgent.Printing\PrintAgent.Printing.csproj" />
    <ProjectReference Include="..\PrintAgent.Core\PrintAgent.Core.csproj" />
    <ProjectReference Include="..\PrintAgent.Transport\PrintAgent.Transport.csproj" />
  </ItemGroup>
</Project>
